HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

setopt autocd extendedglob notify appendhistory correct_all nomatch
unsetopt beep
bindkey -e

# Completition stuff
zstyle :compinstall filename '~/.zshrc'
zstyle ':completion:*' rehash true

autoload -Uz compinit promptinit
compinit
promptinit

# Plugins
source ~/.antigen.zsh

antigen bundle zdharma/fast-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

#antigen theme eendroroy/alien-minimal
antigen theme yardnsm/blox-zsh-theme

antigen bundle zsh-users/zsh-completions
antigen bundle hlissner/zsh-autopair
antigen bundle arzzen/calc.plugin.zsh
antigen bundle zuxfoucault/colored-man-pages_mod
antigen bundle zpm-zsh/colors
antigen bundle popstas/zsh-command-time

antigen apply

# Keys
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line


#----- Alias -----#
alias ls="ls --color --group-directories-first"
alias l="ls"
alias la="ls -la"
alias ll="ls -l"
alias pacman="pacman --color auto"

alias gia="git add"
alias gc="git commit"
alias gp="git push"

alias vim="nvim"
alias subl="subl3"

export BLOX_SEG__UPPER_RIGHT=(bgjobs)

